databases:
  - name: wovenry-db
    plan: free
    databaseName: wovenry
    user: wovenry

services:
  - type: web
    name: wovenry
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wovenry-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: wovenry
          property: host
      - key: PYTHON_VERSION
        value: "3.13.0"
