# Generated by Django 6.0.2 on 2026-03-02 19:02

from django.db import migrations
from django.utils.text import slugify


CATEGORIES = [
    "Strategy", "Legal", "Writing", "Coding", "Product",
    "Academic", "Marketing", "Finance", "HR", "Sales",
    "Operations", "Design", "Data", "Research",
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    for name in CATEGORIES:
        Category.objects.get_or_create(name=name, defaults={"slug": slugify(name)})


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Category.objects.filter(slug__in=[slugify(n) for n in CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
